import { useState, useEffect } from "react";
import { TeamItem } from "./TeamItems";
import "./styles.css";
// import { searchTreeNodePath } from "./utils";
// import { cloneDeep } from "lodash";
import TreeModel from "tree-model";

const config = {
  id: "root",
  name: "root",
  children: [
    {
      id: 0,
      level: "1",
      workorder_base_id: "W42474",
      rm_part_id: "950259-1",
      part_id: "950259-1",
      class: "I",
      type: "O",
      trace_id: "W42475",
      search_trace_id: "W42475",
      wo_count: 1,
      po_count: 0,
      children: [
        {
          id: 1,
          level: "2",
          workorder_base_id: "W42475",
          rm_part_id: "130359-1",
          part_id: "130359-1",
          class: "I",
          type: "O",
          trace_id: "W42476",
          search_trace_id: "W42476",
          wo_count: 3,
          po_count: 0,
          children: [
            {
              id: 31,
              level: "3",
              workorder_base_id: "W42476",
              rm_part_id: "AL6061T6511-R1.500X4.000",
              part_id: "AL6061T6511-R1.500X4.000",
              class: "I",
              type: "O",
              trace_id: "PO09694-1",
              search_trace_id: "PO09694",
              wo_count: 0,
              po_count: 2,
              children: []
            }
          ]
        },
        {
          id: 2,
          level: "2",
          workorder_base_id: "W42475",
          rm_part_id: "190069-7",
          part_id: "190069-7",
          class: "I",
          type: "O",
          trace_id: "PO13075",
          search_trace_id: "PO13075",
          wo_count: 0,
          po_count: 4,
          children: []
        },
        {
          id: 3,
          level: "2",
          workorder_base_id: "W42475",
          rm_part_id: "190069-7",
          part_id: "190069-7",
          class: "I",
          type: "O",
          trace_id: "PO19606",
          search_trace_id: "PO19606",
          wo_count: 0,
          po_count: 4,
          children: []
        },
        {
          id: 4,
          level: "2",
          workorder_base_id: "W42475",
          rm_part_id: "190424-1",
          part_id: "190424-1",
          class: "I",
          type: "O",
          trace_id: "MIG17014",
          search_trace_id: "MIG17014",
          wo_count: 0,
          po_count: 0,
          children: []
        },
        {
          id: 5,
          level: "2",
          workorder_base_id: "W42475",
          rm_part_id: "190424-1",
          part_id: "190424-1",
          class: "I",
          type: "O",
          trace_id: "PO19714",
          search_trace_id: "PO19714",
          wo_count: 0,
          po_count: 4,
          children: []
        },
        {
          id: 6,
          level: "2",
          workorder_base_id: "W42475",
          rm_part_id: "190424-3",
          part_id: "190424-3",
          class: "I",
          type: "O",
          trace_id: "MIG17016",
          search_trace_id: "MIG17016",
          wo_count: 0,
          po_count: 0,
          children: []
        },
        {
          id: 7,
          level: "2",
          workorder_base_id: "W42475",
          rm_part_id: "190424-4",
          part_id: "190424-4",
          class: "I",
          type: "O",
          trace_id: "PO20825",
          search_trace_id: "PO20825",
          wo_count: 0,
          po_count: 2,
          children: []
        },
        {
          id: 8,
          level: "2",
          workorder_base_id: "W42475",
          rm_part_id: "740172-045-AL6061",
          part_id: "740172-045-AL6061",
          class: "I",
          type: "O",
          trace_id: "W42481",
          search_trace_id: "W42481",
          wo_count: 1,
          po_count: 0,
          children: [
            {
              id: 37,
              level: "3",
              workorder_base_id: "W42481",
              rm_part_id: "AL6061T651-R0.500X2.500",
              part_id: "AL6061T651-R0.500X2.500",
              class: "I",
              type: "O",
              trace_id: "po00442",
              search_trace_id: "po00442",
              wo_count: 0,
              po_count: 7,
              children: []
            }
          ]
        },
        {
          id: 9,
          level: "2",
          workorder_base_id: "W42475",
          rm_part_id: "740173-050-AL4032",
          part_id: "740173-050-AL4032",
          class: "I",
          type: "O",
          trace_id: "W42482",
          search_trace_id: "W42482",
          wo_count: 1,
          po_count: 0,
          children: [
            {
              id: 38,
              level: "3",
              workorder_base_id: "W42482",
              rm_part_id: "AL4032-R0.750X6.000",
              part_id: "AL4032-R0.750X6.000",
              class: "I",
              type: "O",
              trace_id: "PO09750-1",
              search_trace_id: "PO09750",
              wo_count: 0,
              po_count: 1,
              children: []
            }
          ]
        },
        {
          id: 10,
          level: "2",
          workorder_base_id: "W42475",
          rm_part_id: "930196-21",
          part_id: "930196-21",
          class: "I",
          type: "O",
          trace_id: "MIG14159",
          search_trace_id: "MIG14159",
          wo_count: 0,
          po_count: 0,
          children: []
        },
        {
          id: 11,
          level: "2",
          workorder_base_id: "W42475",
          rm_part_id: "940018-081T",
          part_id: "940018-081T",
          class: "I",
          type: "O",
          trace_id: "W21363/1",
          search_trace_id: "W21363",
          wo_count: 1,
          po_count: 0,
          children: []
        },
        {
          id: 12,
          level: "2",
          workorder_base_id: "W42475",
          rm_part_id: "940018-081T",
          part_id: "940018-081T",
          class: "I",
          type: "O",
          trace_id: "W42236",
          search_trace_id: "W42236",
          wo_count: 1,
          po_count: 0,
          children: [
            {
              id: 26,
              level: "3",
              workorder_base_id: "W42236",
              rm_part_id: "110049-1",
              part_id: "110049-1",
              class: "I",
              type: "O",
              trace_id: "PO14579",
              search_trace_id: "PO14579",
              wo_count: 0,
              po_count: 4,
              children: []
            },
            {
              id: 27,
              level: "3",
              workorder_base_id: "W42236",
              rm_part_id: "150118-1",
              part_id: "150118-1",
              class: "I",
              type: "O",
              trace_id: "W31242",
              search_trace_id: "W31242",
              wo_count: 3,
              po_count: 0,
              children: [
                {
                  id: 39,
                  level: "4",
                  workorder_base_id: "W31242",
                  rm_part_id: "090000-6-D.250",
                  part_id: "090000-6-D.250",
                  class: "I",
                  type: "O",
                  trace_id: "W31243/1",
                  search_trace_id: "W31243",
                  wo_count: 2,
                  po_count: 0,
                  children: []
                }
              ]
            },
            {
              id: 28,
              level: "3",
              workorder_base_id: "W42236",
              rm_part_id: "190004-1",
              part_id: "190004-1",
              class: "I",
              type: "O",
              trace_id: "PO14494",
              search_trace_id: "PO14494",
              wo_count: 0,
              po_count: 9,
              children: []
            },
            {
              id: 29,
              level: "3",
              workorder_base_id: "W42236",
              rm_part_id: "190047-4",
              part_id: "190047-4",
              class: "I",
              type: "O",
              trace_id: "MIG16635",
              search_trace_id: "MIG16635",
              wo_count: 0,
              po_count: 0,
              children: []
            },
            {
              id: 30,
              level: "3",
              workorder_base_id: "W42236",
              rm_part_id: "920031-083",
              part_id: "920031-083",
              class: "I",
              type: "O",
              trace_id: "W42237",
              search_trace_id: "W42237",
              wo_count: 2,
              po_count: 0,
              children: [
                {
                  id: 41,
                  level: "4",
                  workorder_base_id: "W42237",
                  rm_part_id: "920031-154RU",
                  part_id: "920031-154RU",
                  class: "I",
                  type: "O",
                  trace_id: "W21365/1",
                  search_trace_id: "W21365",
                  wo_count: 2,
                  po_count: 0,
                  children: []
                }
              ]
            }
          ]
        },
        {
          id: 13,
          level: "2",
          workorder_base_id: "W42475",
          rm_part_id: "940166-053T",
          part_id: "940166-053T",
          class: "I",
          type: "O",
          trace_id: "W35844",
          search_trace_id: "W35844",
          wo_count: 2,
          po_count: 0,
          children: [
            {
              id: 16,
              level: "3",
              workorder_base_id: "W35844",
              rm_part_id: "110098-4",
              part_id: "110098-4",
              class: "I",
              type: "O",
              trace_id: "MIG15146",
              search_trace_id: "MIG15146",
              wo_count: 0,
              po_count: 0,
              children: []
            },
            {
              id: 17,
              level: "3",
              workorder_base_id: "W35844",
              rm_part_id: "150452-1",
              part_id: "150452-1",
              class: "I",
              type: "O",
              trace_id: "W20403/1",
              search_trace_id: "W20403",
              wo_count: 3,
              po_count: 0,
              children: []
            },
            {
              id: 18,
              level: "3",
              workorder_base_id: "W35844",
              rm_part_id: "190047-12",
              part_id: "190047-12",
              class: "I",
              type: "O",
              trace_id: "MIG16632",
              search_trace_id: "MIG16632",
              wo_count: 0,
              po_count: 0,
              children: []
            },
            {
              id: 19,
              level: "3",
              workorder_base_id: "W35844",
              rm_part_id: "190424-2",
              part_id: "190424-2",
              class: "I",
              type: "O",
              trace_id: "MIG17015",
              search_trace_id: "MIG17015",
              wo_count: 0,
              po_count: 0,
              children: []
            },
            {
              id: 20,
              level: "3",
              workorder_base_id: "W35844",
              rm_part_id: "920074-055",
              part_id: "920074-055",
              class: "I",
              type: "O",
              trace_id: "W20404/1",
              search_trace_id: "W20404",
              wo_count: 1,
              po_count: 0,
              children: []
            }
          ]
        },
        {
          id: 14,
          level: "2",
          workorder_base_id: "W42475",
          rm_part_id: "940166-107T",
          part_id: "940166-107T",
          class: "I",
          type: "O",
          trace_id: "W42234",
          search_trace_id: "W42234",
          wo_count: 1,
          po_count: 0,
          children: [
            {
              id: 21,
              level: "3",
              workorder_base_id: "W42234",
              rm_part_id: "110098-4",
              part_id: "110098-4",
              class: "I",
              type: "O",
              trace_id: "MIG15146",
              search_trace_id: "MIG15146",
              wo_count: 0,
              po_count: 0,
              children: []
            },
            {
              id: 22,
              level: "3",
              workorder_base_id: "W42234",
              rm_part_id: "150452-1",
              part_id: "150452-1",
              class: "I",
              type: "O",
              trace_id: "W42235",
              search_trace_id: "W42235",
              wo_count: 2,
              po_count: 0,
              children: [
                {
                  id: 40,
                  level: "4",
                  workorder_base_id: "W42235",
                  rm_part_id: "090000-6-D.250",
                  part_id: "090000-6-D.250",
                  class: "I",
                  type: "O",
                  trace_id: "W42477",
                  search_trace_id: "W42477",
                  wo_count: 2,
                  po_count: 0,
                  children: [
                    {
                      id: 42,
                      level: "4",
                      workorder_base_id: "W42477",
                      rm_part_id: "090000-6",
                      part_id: "090000-6",
                      class: "I",
                      type: "O",
                      trace_id: "PO14008",
                      search_trace_id: "PO14008",
                      wo_count: 0,
                      po_count: 3,
                      children: []
                    },{
                      id: 45,
                      level: "5",
                      workorder_base_id: "PO14008",
                      rm_part_id: "090000-6",
                      part_id: "090000-6",
                      class: "I",
                      type: "O",
                      trace_id: "PO14000",
                      search_trace_id: "PO14000",
                      wo_count: 0,
                      po_count: 3,
                      children: []
                    },
                    {
                      id: 45,
                      level: "5",
                      workorder_base_id: "PO14008",
                      rm_part_id: "090000-6",
                      part_id: "090000-6",
                      class: "I",
                      type: "O",
                      trace_id: "PO14000",
                      search_trace_id: "PO14000",
                      wo_count: 0,
                      po_count: 3,
                      children: []
                    },
                    {
                      id: 45,
                      level: "5",
                      workorder_base_id: "PO14008",
                      rm_part_id: "090000-6",
                      part_id: "090000-6",
                      class: "I",
                      type: "O",
                      trace_id: "PO14000",
                      search_trace_id: "PO14000",
                      wo_count: 0,
                      po_count: 3,
                      children: [{
                        id: 45,
                        level: "5",
                        workorder_base_id: "PO14008",
                        rm_part_id: "090000-6",
                        part_id: "090000-6",
                        class: "I",
                        type: "O",
                        trace_id: "PO14000",
                        search_trace_id: "PO14000",
                        wo_count: 0,
                        po_count: 3,
                        children: []
                      },
                      {
                        id: 45,
                        level: "5",
                        workorder_base_id: "PO14008",
                        rm_part_id: "090000-6",
                        part_id: "090000-6",
                        class: "I",
                        type: "O",
                        trace_id: "PO14000",
                        search_trace_id: "PO14000",
                        wo_count: 0,
                        po_count: 3,
                        children: []
                      },
                      {
                        id: 45,
                        level: "5",
                        workorder_base_id: "PO14008",
                        rm_part_id: "090000-6",
                        part_id: "090000-6",
                        class: "I",
                        type: "O",
                        trace_id: "PO14000",
                        search_trace_id: "PO14000",
                        wo_count: 0,
                        po_count: 3,
                        children: [{
                          id: 45,
                          level: "5",
                          workorder_base_id: "PO14008",
                          rm_part_id: "090000-6",
                          part_id: "090000-6",
                          class: "I",
                          type: "O",
                          trace_id: "PO14000",
                          search_trace_id: "PO14000",
                          wo_count: 0,
                          po_count: 3,
                          children: []
                        },
                        {
                          id: 45,
                          level: "5",
                          workorder_base_id: "PO14008",
                          rm_part_id: "090000-6",
                          part_id: "090000-6",
                          class: "I",
                          type: "O",
                          trace_id: "PO14000",
                          search_trace_id: "PO14000",
                          wo_count: 0,
                          po_count: 3,
                          children: []
                        },
                        {
                          id: 45,
                          level: "5",
                          workorder_base_id: "PO14008",
                          rm_part_id: "090000-6",
                          part_id: "090000-6",
                          class: "I",
                          type: "O",
                          trace_id: "PO14000",
                          search_trace_id: "PO14000",
                          wo_count: 0,
                          po_count: 3,
                          children: []
                        }]
                      }]
                    }
                  ]
                }
              ]
            },
            {
              id: 23,
              level: "3",
              workorder_base_id: "W42234",
              rm_part_id: "190047-12",
              part_id: "190047-12",
              class: "I",
              type: "O",
              trace_id: "MIG16632",
              search_trace_id: "MIG16632",
              wo_count: 0,
              po_count: 0,
              children: [{
                id: 45,
                level: "5",
                workorder_base_id: "PO14008",
                rm_part_id: "090000-6",
                part_id: "090000-6",
                class: "I",
                type: "O",
                trace_id: "PO14000",
                search_trace_id: "PO14000",
                wo_count: 0,
                po_count: 3,
                children: []
              },
              {
                id: 45,
                level: "5",
                workorder_base_id: "PO14008",
                rm_part_id: "090000-6",
                part_id: "090000-6",
                class: "I",
                type: "O",
                trace_id: "PO14000",
                search_trace_id: "PO14000",
                wo_count: 0,
                po_count: 3,
                children: []
              },
              {
                id: 45,
                level: "5",
                workorder_base_id: "PO14008",
                rm_part_id: "090000-6",
                part_id: "090000-6",
                class: "I",
                type: "O",
                trace_id: "PO14000",
                search_trace_id: "PO14000",
                wo_count: 0,
                po_count: 3,
                children: []
              }]
            },
            {
              id: 24,
              level: "3",
              workorder_base_id: "W42234",
              rm_part_id: "190424-2",
              part_id: "190424-2",
              class: "I",
              type: "O",
              trace_id: "MIG17015",
              search_trace_id: "MIG17015",
              wo_count: 0,
              po_count: 0,
              children: [{
                id: 45,
                level: "5",
                workorder_base_id: "PO14008",
                rm_part_id: "090000-6",
                part_id: "090000-6",
                class: "I",
                type: "O",
                trace_id: "PO14000",
                search_trace_id: "PO14000",
                wo_count: 0,
                po_count: 3,
                children: []
              },
              {
                id: 45,
                level: "5",
                workorder_base_id: "PO14008",
                rm_part_id: "090000-6",
                part_id: "090000-6",
                class: "I",
                type: "O",
                trace_id: "PO14000",
                search_trace_id: "PO14000",
                wo_count: 0,
                po_count: 3,
                children: []
              },
              {
                id: 45,
                level: "5",
                workorder_base_id: "PO14008",
                rm_part_id: "090000-6",
                part_id: "090000-6",
                class: "I",
                type: "O",
                trace_id: "PO14000",
                search_trace_id: "PO14000",
                wo_count: 0,
                po_count: 3,
                children: [{
                  id: 45,
                  level: "5",
                  workorder_base_id: "PO14008",
                  rm_part_id: "090000-6",
                  part_id: "090000-6",
                  class: "I",
                  type: "O",
                  trace_id: "PO14000",
                  search_trace_id: "PO14000",
                  wo_count: 0,
                  po_count: 3,
                  children: []
                },
                {
                  id: 45,
                  level: "5",
                  workorder_base_id: "PO14008",
                  rm_part_id: "090000-6",
                  part_id: "090000-6",
                  class: "I",
                  type: "O",
                  trace_id: "PO14000",
                  search_trace_id: "PO14000",
                  wo_count: 0,
                  po_count: 3,
                  children: []
                },
                {
                  id: 45,
                  level: "5",
                  workorder_base_id: "PO14008",
                  rm_part_id: "090000-6",
                  part_id: "090000-6",
                  class: "I",
                  type: "O",
                  trace_id: "PO14000",
                  search_trace_id: "PO14000",
                  wo_count: 0,
                  po_count: 3,
                  children: []
                }]
              }]
            },
            {
              id: 25,
              level: "3",
              workorder_base_id: "W42234",
              rm_part_id: "920074-109",
              part_id: "920074-109",
              class: "I",
              type: "O",
              trace_id: "MIG17495",
              search_trace_id: "MIG17495",
              wo_count: 0,
              po_count: 0,
              children: [{
                id: 45,
                level: "5",
                workorder_base_id: "PO14008",
                rm_part_id: "090000-6",
                part_id: "090000-6",
                class: "I",
                type: "O",
                trace_id: "PO14000",
                search_trace_id: "PO14000",
                wo_count: 0,
                po_count: 3,
                children: []
              },
              {
                id: 45,
                level: "5",
                workorder_base_id: "PO14008",
                rm_part_id: "090000-6",
                part_id: "090000-6",
                class: "I",
                type: "O",
                trace_id: "PO14000",
                search_trace_id: "PO14000",
                wo_count: 0,
                po_count: 3,
                children: []
              },
              {
                id: 45,
                level: "5",
                workorder_base_id: "PO14008",
                rm_part_id: "090000-6",
                part_id: "090000-6",
                class: "I",
                type: "O",
                trace_id: "PO14000",
                search_trace_id: "PO14000",
                wo_count: 0,
                po_count: 3,
                children: []
              }]
            }
          ]
        },
        {
          id: 15,
          level: "2",
          workorder_base_id: "W42475",
          rm_part_id: "940166-120T",
          part_id: "940166-120T",
          class: "I",
          type: "O",
          trace_id: "W42478",
          search_trace_id: "W42478",
          wo_count: 1,
          po_count: 0,
          children: [
            {
              id: 32,
              level: "3",
              workorder_base_id: "W42478",
              rm_part_id: "110098-4",
              part_id: "110098-4",
              class: "I",
              type: "O",
              trace_id: "MIG15146",
              search_trace_id: "MIG15146",
              wo_count: 0,
              po_count: 0,
              children: [{
                id: 45,
                level: "5",
                workorder_base_id: "PO14008",
                rm_part_id: "090000-6",
                part_id: "090000-6",
                class: "I",
                type: "O",
                trace_id: "PO14000",
                search_trace_id: "PO14000",
                wo_count: 0,
                po_count: 3,
                children: []
              },
              {
                id: 45,
                level: "5",
                workorder_base_id: "PO14008",
                rm_part_id: "090000-6",
                part_id: "090000-6",
                class: "I",
                type: "O",
                trace_id: "PO14000",
                search_trace_id: "PO14000",
                wo_count: 0,
                po_count: 3,
                children: []
              },
              {
                id: 45,
                level: "5",
                workorder_base_id: "PO14008",
                rm_part_id: "090000-6",
                part_id: "090000-6",
                class: "I",
                type: "O",
                trace_id: "PO14000",
                search_trace_id: "PO14000",
                wo_count: 0,
                po_count: 3,
                children: []
              }]
            },
            {
              id: 33,
              level: "3",
              workorder_base_id: "W42478",
              rm_part_id: "150452-1",
              part_id: "150452-1",
              class: "I",
              type: "O",
              trace_id: "W42235",
              search_trace_id: "W42235",
              wo_count: 2,
              po_count: 0,
              children: []
            },
            {
              id: 34,
              level: "3",
              workorder_base_id: "W42478",
              rm_part_id: "190047-12",
              part_id: "190047-12",
              class: "I",
              type: "O",
              trace_id: "MIG16632",
              search_trace_id: "MIG16632",
              wo_count: 0,
              po_count: 0,
              children: []
            },
            {
              id: 35,
              level: "3",
              workorder_base_id: "W42478",
              rm_part_id: "190424-2",
              part_id: "190424-2",
              class: "I",
              type: "O",
              trace_id: "MIG17015",
              search_trace_id: "MIG17015",
              wo_count: 0,
              po_count: 0,
              children: []
            },
            {
              id: 36,
              level: "3",
              workorder_base_id: "W42478",
              rm_part_id: "920074-122",
              part_id: "920074-122",
              class: "I",
              type: "O",
              trace_id: "W42479",
              search_trace_id: "W42479",
              wo_count: 3,
              po_count: 0,
              children: [
                {
                  id: 43,
                  level: "4",
                  workorder_base_id: "W42479",
                  rm_part_id: "140317-1",
                  part_id: "140317-1",
                  class: "I",
                  type: "O",
                  trace_id: "PO19354",
                  search_trace_id: "PO19354",
                  wo_count: 0,
                  po_count: 4,
                  children: []
                }
              ]
            }
          ]
        }
      ]
    },
    {
      id: 1,
      level: "2",
      workorder_base_id: "W42475",
      rm_part_id: "130359-1",
      part_id: "130359-1",
      class: "I",
      type: "O",
      trace_id: "W42476",
      search_trace_id: "W42476",
      wo_count: 3,
      po_count: 0,
      children: [
        {
          id: 31,
          level: "3",
          workorder_base_id: "W42476",
          rm_part_id: "AL6061T6511-R1.500X4.000",
          part_id: "AL6061T6511-R1.500X4.000",
          class: "I",
          type: "O",
          trace_id: "PO09694-1",
          search_trace_id: "PO09694",
          wo_count: 0,
          po_count: 2,
          children: []
        }
      ]
    },
    {
      id: 2,
      level: "2",
      workorder_base_id: "W42475",
      rm_part_id: "190069-7",
      part_id: "190069-7",
      class: "I",
      type: "O",
      trace_id: "PO13075",
      search_trace_id: "PO13075",
      wo_count: 0,
      po_count: 4,
      children: []
    },
    {
      id: 3,
      level: "2",
      workorder_base_id: "W42475",
      rm_part_id: "190069-7",
      part_id: "190069-7",
      class: "I",
      type: "O",
      trace_id: "PO19606",
      search_trace_id: "PO19606",
      wo_count: 0,
      po_count: 4,
      children: []
    },
    {
      id: 4,
      level: "2",
      workorder_base_id: "W42475",
      rm_part_id: "190424-1",
      part_id: "190424-1",
      class: "I",
      type: "O",
      trace_id: "MIG17014",
      search_trace_id: "MIG17014",
      wo_count: 0,
      po_count: 0,
      children: []
    },
    {
      id: 5,
      level: "2",
      workorder_base_id: "W42475",
      rm_part_id: "190424-1",
      part_id: "190424-1",
      class: "I",
      type: "O",
      trace_id: "PO19714",
      search_trace_id: "PO19714",
      wo_count: 0,
      po_count: 4,
      children: []
    },
    {
      id: 6,
      level: "2",
      workorder_base_id: "W42475",
      rm_part_id: "190424-3",
      part_id: "190424-3",
      class: "I",
      type: "O",
      trace_id: "MIG17016",
      search_trace_id: "MIG17016",
      wo_count: 0,
      po_count: 0,
      children: []
    },
    {
      id: 7,
      level: "2",
      workorder_base_id: "W42475",
      rm_part_id: "190424-4",
      part_id: "190424-4",
      class: "I",
      type: "O",
      trace_id: "PO20825",
      search_trace_id: "PO20825",
      wo_count: 0,
      po_count: 2,
      children: []
    },
    {
      id: 8,
      level: "2",
      workorder_base_id: "W42475",
      rm_part_id: "740172-045-AL6061",
      part_id: "740172-045-AL6061",
      class: "I",
      type: "O",
      trace_id: "W42481",
      search_trace_id: "W42481",
      wo_count: 1,
      po_count: 0,
      children: [
        {
          id: 37,
          level: "3",
          workorder_base_id: "W42481",
          rm_part_id: "AL6061T651-R0.500X2.500",
          part_id: "AL6061T651-R0.500X2.500",
          class: "I",
          type: "O",
          trace_id: "po00442",
          search_trace_id: "po00442",
          wo_count: 0,
          po_count: 7,
          children: []
        }
      ]
    },
    {
      id: 9,
      level: "2",
      workorder_base_id: "W42475",
      rm_part_id: "740173-050-AL4032",
      part_id: "740173-050-AL4032",
      class: "I",
      type: "O",
      trace_id: "W42482",
      search_trace_id: "W42482",
      wo_count: 1,
      po_count: 0,
      children: [
        {
          id: 38,
          level: "3",
          workorder_base_id: "W42482",
          rm_part_id: "AL4032-R0.750X6.000",
          part_id: "AL4032-R0.750X6.000",
          class: "I",
          type: "O",
          trace_id: "PO09750-1",
          search_trace_id: "PO09750",
          wo_count: 0,
          po_count: 1,
          children: []
        }
      ]
    },
    {
      id: 10,
      level: "2",
      workorder_base_id: "W42475",
      rm_part_id: "930196-21",
      part_id: "930196-21",
      class: "I",
      type: "O",
      trace_id: "MIG14159",
      search_trace_id: "MIG14159",
      wo_count: 0,
      po_count: 0,
      children: []
    },
    {
      id: 11,
      level: "2",
      workorder_base_id: "W42475",
      rm_part_id: "940018-081T",
      part_id: "940018-081T",
      class: "I",
      type: "O",
      trace_id: "W21363/1",
      search_trace_id: "W21363",
      wo_count: 1,
      po_count: 0,
      children: []
    },
    {
      id: 12,
      level: "2",
      workorder_base_id: "W42475",
      rm_part_id: "940018-081T",
      part_id: "940018-081T",
      class: "I",
      type: "O",
      trace_id: "W42236",
      search_trace_id: "W42236",
      wo_count: 1,
      po_count: 0,
      children: [
        {
          id: 26,
          level: "3",
          workorder_base_id: "W42236",
          rm_part_id: "110049-1",
          part_id: "110049-1",
          class: "I",
          type: "O",
          trace_id: "PO14579",
          search_trace_id: "PO14579",
          wo_count: 0,
          po_count: 4,
          children: []
        },
        {
          id: 27,
          level: "3",
          workorder_base_id: "W42236",
          rm_part_id: "150118-1",
          part_id: "150118-1",
          class: "I",
          type: "O",
          trace_id: "W31242",
          search_trace_id: "W31242",
          wo_count: 3,
          po_count: 0,
          children: [
            {
              id: 39,
              level: "4",
              workorder_base_id: "W31242",
              rm_part_id: "090000-6-D.250",
              part_id: "090000-6-D.250",
              class: "I",
              type: "O",
              trace_id: "W31243/1",
              search_trace_id: "W31243",
              wo_count: 2,
              po_count: 0,
              children: []
            }
          ]
        },
        {
          id: 28,
          level: "3",
          workorder_base_id: "W42236",
          rm_part_id: "190004-1",
          part_id: "190004-1",
          class: "I",
          type: "O",
          trace_id: "PO14494",
          search_trace_id: "PO14494",
          wo_count: 0,
          po_count: 9,
          children: []
        },
        {
          id: 29,
          level: "3",
          workorder_base_id: "W42236",
          rm_part_id: "190047-4",
          part_id: "190047-4",
          class: "I",
          type: "O",
          trace_id: "MIG16635",
          search_trace_id: "MIG16635",
          wo_count: 0,
          po_count: 0,
          children: []
        },
        {
          id: 30,
          level: "3",
          workorder_base_id: "W42236",
          rm_part_id: "920031-083",
          part_id: "920031-083",
          class: "I",
          type: "O",
          trace_id: "W42237",
          search_trace_id: "W42237",
          wo_count: 2,
          po_count: 0,
          children: [
            {
              id: 41,
              level: "4",
              workorder_base_id: "W42237",
              rm_part_id: "920031-154RU",
              part_id: "920031-154RU",
              class: "I",
              type: "O",
              trace_id: "W21365/1",
              search_trace_id: "W21365",
              wo_count: 2,
              po_count: 0,
              children: []
            }
          ]
        }
      ]
    },
    {
      id: 13,
      level: "2",
      workorder_base_id: "W42475",
      rm_part_id: "940166-053T",
      part_id: "940166-053T",
      class: "I",
      type: "O",
      trace_id: "W35844",
      search_trace_id: "W35844",
      wo_count: 2,
      po_count: 0,
      children: [
        {
          id: 16,
          level: "3",
          workorder_base_id: "W35844",
          rm_part_id: "110098-4",
          part_id: "110098-4",
          class: "I",
          type: "O",
          trace_id: "MIG15146",
          search_trace_id: "MIG15146",
          wo_count: 0,
          po_count: 0,
          children: []
        },
        {
          id: 17,
          level: "3",
          workorder_base_id: "W35844",
          rm_part_id: "150452-1",
          part_id: "150452-1",
          class: "I",
          type: "O",
          trace_id: "W20403/1",
          search_trace_id: "W20403",
          wo_count: 3,
          po_count: 0,
          children: []
        },
        {
          id: 18,
          level: "3",
          workorder_base_id: "W35844",
          rm_part_id: "190047-12",
          part_id: "190047-12",
          class: "I",
          type: "O",
          trace_id: "MIG16632",
          search_trace_id: "MIG16632",
          wo_count: 0,
          po_count: 0,
          children: []
        },
        {
          id: 19,
          level: "3",
          workorder_base_id: "W35844",
          rm_part_id: "190424-2",
          part_id: "190424-2",
          class: "I",
          type: "O",
          trace_id: "MIG17015",
          search_trace_id: "MIG17015",
          wo_count: 0,
          po_count: 0,
          children: []
        },
        {
          id: 20,
          level: "3",
          workorder_base_id: "W35844",
          rm_part_id: "920074-055",
          part_id: "920074-055",
          class: "I",
          type: "O",
          trace_id: "W20404/1",
          search_trace_id: "W20404",
          wo_count: 1,
          po_count: 0,
          children: []
        }
      ]
    },
    {
      id: 14,
      level: "2",
      workorder_base_id: "W42475",
      rm_part_id: "940166-107T",
      part_id: "940166-107T",
      class: "I",
      type: "O",
      trace_id: "W42234",
      search_trace_id: "W42234",
      wo_count: 1,
      po_count: 0,
      children: [
        {
          id: 21,
          level: "3",
          workorder_base_id: "W42234",
          rm_part_id: "110098-4",
          part_id: "110098-4",
          class: "I",
          type: "O",
          trace_id: "MIG15146",
          search_trace_id: "MIG15146",
          wo_count: 0,
          po_count: 0,
          children: []
        },
        {
          id: 22,
          level: "3",
          workorder_base_id: "W42234",
          rm_part_id: "150452-1",
          part_id: "150452-1",
          class: "I",
          type: "O",
          trace_id: "W42235",
          search_trace_id: "W42235",
          wo_count: 2,
          po_count: 0,
          children: [
            {
              id: 40,
              level: "4",
              workorder_base_id: "W42235",
              rm_part_id: "090000-6-D.250",
              part_id: "090000-6-D.250",
              class: "I",
              type: "O",
              trace_id: "W42477",
              search_trace_id: "W42477",
              wo_count: 2,
              po_count: 0,
              children: [
                {
                  id: 42,
                  level: "4",
                  workorder_base_id: "W42477",
                  rm_part_id: "090000-6",
                  part_id: "090000-6",
                  class: "I",
                  type: "O",
                  trace_id: "PO14008",
                  search_trace_id: "PO14008",
                  wo_count: 0,
                  po_count: 3,
                  children: []
                }
              ]
            }
          ]
        },
        {
          id: 23,
          level: "3",
          workorder_base_id: "W42234",
          rm_part_id: "190047-12",
          part_id: "190047-12",
          class: "I",
          type: "O",
          trace_id: "MIG16632",
          search_trace_id: "MIG16632",
          wo_count: 0,
          po_count: 0,
          children: []
        },
        {
          id: 24,
          level: "3",
          workorder_base_id: "W42234",
          rm_part_id: "190424-2",
          part_id: "190424-2",
          class: "I",
          type: "O",
          trace_id: "MIG17015",
          search_trace_id: "MIG17015",
          wo_count: 0,
          po_count: 0,
          children: []
        },
        {
          id: 25,
          level: "3",
          workorder_base_id: "W42234",
          rm_part_id: "920074-109",
          part_id: "920074-109",
          class: "I",
          type: "O",
          trace_id: "MIG17495",
          search_trace_id: "MIG17495",
          wo_count: 0,
          po_count: 0,
          children: []
        }
      ]
    },
    {
      id: 15,
      level: "2",
      workorder_base_id: "W42475",
      rm_part_id: "940166-120T",
      part_id: "940166-120T",
      class: "I",
      type: "O",
      trace_id: "W42478",
      search_trace_id: "W42478",
      wo_count: 1,
      po_count: 0,
      children: [
        {
          id: 32,
          level: "3",
          workorder_base_id: "W42478",
          rm_part_id: "110098-4",
          part_id: "110098-4",
          class: "I",
          type: "O",
          trace_id: "MIG15146",
          search_trace_id: "MIG15146",
          wo_count: 0,
          po_count: 0,
          children: []
        },
        {
          id: 33,
          level: "3",
          workorder_base_id: "W42478",
          rm_part_id: "150452-1",
          part_id: "150452-1",
          class: "I",
          type: "O",
          trace_id: "W42235",
          search_trace_id: "W42235",
          wo_count: 2,
          po_count: 0,
          children: []
        },
        {
          id: 34,
          level: "3",
          workorder_base_id: "W42478",
          rm_part_id: "190047-12",
          part_id: "190047-12",
          class: "I",
          type: "O",
          trace_id: "MIG16632",
          search_trace_id: "MIG16632",
          wo_count: 0,
          po_count: 0,
          children: []
        },
        {
          id: 35,
          level: "3",
          workorder_base_id: "W42478",
          rm_part_id: "190424-2",
          part_id: "190424-2",
          class: "I",
          type: "O",
          trace_id: "MIG17015",
          search_trace_id: "MIG17015",
          wo_count: 0,
          po_count: 0,
          children: []
        },
        {
          id: 36,
          level: "3",
          workorder_base_id: "W42478",
          rm_part_id: "920074-122",
          part_id: "920074-122",
          class: "I",
          type: "O",
          trace_id: "W42479",
          search_trace_id: "W42479",
          wo_count: 3,
          po_count: 0,
          children: [
            {
              id: 43,
              level: "4",
              workorder_base_id: "W42479",
              rm_part_id: "140317-1",
              part_id: "140317-1",
              class: "I",
              type: "O",
              trace_id: "PO19354",
              search_trace_id: "PO19354",
              wo_count: 0,
              po_count: 4,
              children: []
            }
          ]
        }
      ]
    },
    {
      id: 16,
      level: "3",
      workorder_base_id: "W35844",
      rm_part_id: "110098-4",
      part_id: "110098-4",
      class: "I",
      type: "O",
      trace_id: "MIG15146",
      search_trace_id: "MIG15146",
      wo_count: 0,
      po_count: 0,
      children: []
    },
    {
      id: 17,
      level: "3",
      workorder_base_id: "W35844",
      rm_part_id: "150452-1",
      part_id: "150452-1",
      class: "I",
      type: "O",
      trace_id: "W20403/1",
      search_trace_id: "W20403",
      wo_count: 3,
      po_count: 0,
      children: []
    },
    {
      id: 18,
      level: "3",
      workorder_base_id: "W35844",
      rm_part_id: "190047-12",
      part_id: "190047-12",
      class: "I",
      type: "O",
      trace_id: "MIG16632",
      search_trace_id: "MIG16632",
      wo_count: 0,
      po_count: 0,
      children: []
    },
    {
      id: 19,
      level: "3",
      workorder_base_id: "W35844",
      rm_part_id: "190424-2",
      part_id: "190424-2",
      class: "I",
      type: "O",
      trace_id: "MIG17015",
      search_trace_id: "MIG17015",
      wo_count: 0,
      po_count: 0,
      children: []
    },
    {
      id: 20,
      level: "3",
      workorder_base_id: "W35844",
      rm_part_id: "920074-055",
      part_id: "920074-055",
      class: "I",
      type: "O",
      trace_id: "W20404/1",
      search_trace_id: "W20404",
      wo_count: 1,
      po_count: 0,
      children: []
    },
    {
      id: 21,
      level: "3",
      workorder_base_id: "W42234",
      rm_part_id: "110098-4",
      part_id: "110098-4",
      class: "I",
      type: "O",
      trace_id: "MIG15146",
      search_trace_id: "MIG15146",
      wo_count: 0,
      po_count: 0,
      children: []
    },
    {
      id: 22,
      level: "3",
      workorder_base_id: "W42234",
      rm_part_id: "150452-1",
      part_id: "150452-1",
      class: "I",
      type: "O",
      trace_id: "W42235",
      search_trace_id: "W42235",
      wo_count: 2,
      po_count: 0,
      children: [
        {
          id: 40,
          level: "4",
          workorder_base_id: "W42235",
          rm_part_id: "090000-6-D.250",
          part_id: "090000-6-D.250",
          class: "I",
          type: "O",
          trace_id: "W42477",
          search_trace_id: "W42477",
          wo_count: 2,
          po_count: 0,
          children: [
            {
              id: 42,
              level: "4",
              workorder_base_id: "W42477",
              rm_part_id: "090000-6",
              part_id: "090000-6",
              class: "I",
              type: "O",
              trace_id: "PO14008",
              search_trace_id: "PO14008",
              wo_count: 0,
              po_count: 3,
              children: []
            }
          ]
        }
      ]
    },
    {
      id: 23,
      level: "3",
      workorder_base_id: "W42234",
      rm_part_id: "190047-12",
      part_id: "190047-12",
      class: "I",
      type: "O",
      trace_id: "MIG16632",
      search_trace_id: "MIG16632",
      wo_count: 0,
      po_count: 0,
      children: []
    },
    {
      id: 24,
      level: "3",
      workorder_base_id: "W42234",
      rm_part_id: "190424-2",
      part_id: "190424-2",
      class: "I",
      type: "O",
      trace_id: "MIG17015",
      search_trace_id: "MIG17015",
      wo_count: 0,
      po_count: 0,
      children: []
    },
    {
      id: 25,
      level: "3",
      workorder_base_id: "W42234",
      rm_part_id: "920074-109",
      part_id: "920074-109",
      class: "I",
      type: "O",
      trace_id: "MIG17495",
      search_trace_id: "MIG17495",
      wo_count: 0,
      po_count: 0,
      children: []
    },
    {
      id: 26,
      level: "3",
      workorder_base_id: "W42236",
      rm_part_id: "110049-1",
      part_id: "110049-1",
      class: "I",
      type: "O",
      trace_id: "PO14579",
      search_trace_id: "PO14579",
      wo_count: 0,
      po_count: 4,
      children: []
    },
    {
      id: 27,
      level: "3",
      workorder_base_id: "W42236",
      rm_part_id: "150118-1",
      part_id: "150118-1",
      class: "I",
      type: "O",
      trace_id: "W31242",
      search_trace_id: "W31242",
      wo_count: 3,
      po_count: 0,
      children: [
        {
          id: 39,
          level: "4",
          workorder_base_id: "W31242",
          rm_part_id: "090000-6-D.250",
          part_id: "090000-6-D.250",
          class: "I",
          type: "O",
          trace_id: "W31243/1",
          search_trace_id: "W31243",
          wo_count: 2,
          po_count: 0,
          children: []
        }
      ]
    },
    {
      id: 28,
      level: "3",
      workorder_base_id: "W42236",
      rm_part_id: "190004-1",
      part_id: "190004-1",
      class: "I",
      type: "O",
      trace_id: "PO14494",
      search_trace_id: "PO14494",
      wo_count: 0,
      po_count: 9,
      children: []
    },
    {
      id: 29,
      level: "3",
      workorder_base_id: "W42236",
      rm_part_id: "190047-4",
      part_id: "190047-4",
      class: "I",
      type: "O",
      trace_id: "MIG16635",
      search_trace_id: "MIG16635",
      wo_count: 0,
      po_count: 0,
      children: []
    },
    {
      id: 30,
      level: "3",
      workorder_base_id: "W42236",
      rm_part_id: "920031-083",
      part_id: "920031-083",
      class: "I",
      type: "O",
      trace_id: "W42237",
      search_trace_id: "W42237",
      wo_count: 2,
      po_count: 0,
      children: [
        {
          id: 41,
          level: "4",
          workorder_base_id: "W42237",
          rm_part_id: "920031-154RU",
          part_id: "920031-154RU",
          class: "I",
          type: "O",
          trace_id: "W21365/1",
          search_trace_id: "W21365",
          wo_count: 2,
          po_count: 0,
          children: []
        }
      ]
    },
    {
      id: 31,
      level: "3",
      workorder_base_id: "W42476",
      rm_part_id: "AL6061T6511-R1.500X4.000",
      part_id: "AL6061T6511-R1.500X4.000",
      class: "I",
      type: "O",
      trace_id: "PO09694-1",
      search_trace_id: "PO09694",
      wo_count: 0,
      po_count: 2,
      children: []
    },
    {
      id: 32,
      level: "3",
      workorder_base_id: "W42478",
      rm_part_id: "110098-4",
      part_id: "110098-4",
      class: "I",
      type: "O",
      trace_id: "MIG15146",
      search_trace_id: "MIG15146",
      wo_count: 0,
      po_count: 0,
      children: []
    },
    {
      id: 33,
      level: "3",
      workorder_base_id: "W42478",
      rm_part_id: "150452-1",
      part_id: "150452-1",
      class: "I",
      type: "O",
      trace_id: "W42235",
      search_trace_id: "W42235",
      wo_count: 2,
      po_count: 0,
      children: []
    },
    {
      id: 34,
      level: "3",
      workorder_base_id: "W42478",
      rm_part_id: "190047-12",
      part_id: "190047-12",
      class: "I",
      type: "O",
      trace_id: "MIG16632",
      search_trace_id: "MIG16632",
      wo_count: 0,
      po_count: 0,
      children: []
    },
    {
      id: 35,
      level: "3",
      workorder_base_id: "W42478",
      rm_part_id: "190424-2",
      part_id: "190424-2",
      class: "I",
      type: "O",
      trace_id: "MIG17015",
      search_trace_id: "MIG17015",
      wo_count: 0,
      po_count: 0,
      children: []
    },
    {
      id: 36,
      level: "3",
      workorder_base_id: "W42478",
      rm_part_id: "920074-122",
      part_id: "920074-122",
      class: "I",
      type: "O",
      trace_id: "W42479",
      search_trace_id: "W42479",
      wo_count: 3,
      po_count: 0,
      children: [
        {
          id: 43,
          level: "4",
          workorder_base_id: "W42479",
          rm_part_id: "140317-1",
          part_id: "140317-1",
          class: "I",
          type: "O",
          trace_id: "PO19354",
          search_trace_id: "PO19354",
          wo_count: 0,
          po_count: 4,
          children: []
        }
      ]
    },
    {
      id: 37,
      level: "3",
      workorder_base_id: "W42481",
      rm_part_id: "AL6061T651-R0.500X2.500",
      part_id: "AL6061T651-R0.500X2.500",
      class: "I",
      type: "O",
      trace_id: "po00442",
      search_trace_id: "po00442",
      wo_count: 0,
      po_count: 7,
      children: []
    },
    {
      id: 38,
      level: "3",
      workorder_base_id: "W42482",
      rm_part_id: "AL4032-R0.750X6.000",
      part_id: "AL4032-R0.750X6.000",
      class: "I",
      type: "O",
      trace_id: "PO09750-1",
      search_trace_id: "PO09750",
      wo_count: 0,
      po_count: 1,
      children: []
    },
    {
      id: 39,
      level: "4",
      workorder_base_id: "W31242",
      rm_part_id: "090000-6-D.250",
      part_id: "090000-6-D.250",
      class: "I",
      type: "O",
      trace_id: "W31243/1",
      search_trace_id: "W31243",
      wo_count: 2,
      po_count: 0,
      children: []
    },
    {
      id: 40,
      level: "4",
      workorder_base_id: "W42235",
      rm_part_id: "090000-6-D.250",
      part_id: "090000-6-D.250",
      class: "I",
      type: "O",
      trace_id: "W42477",
      search_trace_id: "W42477",
      wo_count: 2,
      po_count: 0,
      children: [
        {
          id: 42,
          level: "4",
          workorder_base_id: "W42477",
          rm_part_id: "090000-6",
          part_id: "090000-6",
          class: "I",
          type: "O",
          trace_id: "PO14008",
          search_trace_id: "PO14008",
          wo_count: 0,
          po_count: 3,
          children: []
        }
      ]
    },
    {
      id: 41,
      level: "4",
      workorder_base_id: "W42237",
      rm_part_id: "920031-154RU",
      part_id: "920031-154RU",
      class: "I",
      type: "O",
      trace_id: "W21365/1",
      search_trace_id: "W21365",
      wo_count: 2,
      po_count: 0,
      children: []
    },
    {
      id: 42,
      level: "4",
      workorder_base_id: "W42477",
      rm_part_id: "090000-6",
      part_id: "090000-6",
      class: "I",
      type: "O",
      trace_id: "PO14008",
      search_trace_id: "PO14008",
      wo_count: 0,
      po_count: 3,
      children: []
    },
    {
      id: 43,
      level: "4",
      workorder_base_id: "W42479",
      rm_part_id: "140317-1",
      part_id: "140317-1",
      class: "I",
      type: "O",
      trace_id: "PO19354",
      search_trace_id: "PO19354",
      wo_count: 0,
      po_count: 4,
      children: []
    }
  ]
};

const tree = new TreeModel();
const root = tree.parse(config);
var data = root.all((node) => node.model.id);

const Parent = ({ item, onDragStart, onDragEnd, draggable }) => (
  <div
    className="test"
    // onDragStart={onDragStart}
    // onDragEnd={onDragEnd}
    // draggable={draggable}
  >
    {item.base_id} {item.part_id} &nbsp;
    {item.search_trace_id}
  </div>
);

export default function App() {
  const [path, setPath] = useState([]);
  const tree = new TreeModel();
  const root = tree.parse(config);

  useEffect(() => {
    document.body.className = "currentapp_hr teams";
  }, []);

  const searchItemPath = (id) =>
    root
      .first((node) => node.model.id === id)
      .getPath()
      .filter((node) => "id" in node.model)
      .map((node) => ({
        id: node.model.id,
        index: node.getIndex()
      }));

  const onItemClick = (item) => {
    const path = searchItemPath(item.id);
    setPath(path);
  };

  return (
    <div className="hr-teams">
      <TeamItem
        items={root.model.children}
        onItemClick={onItemClick}
        selectedPath={path}
        itemNode={Parent}
        searchItemPath={searchItemPath}
      />
    </div>
  );
}
